"""empty message

Revision ID: 01e9d8705673
Revises: 6fd0fe6cd843
Create Date: 2023-04-24 11:00:36.770091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e9d8705673'
down_revision = '6fd0fe6cd843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tonic_user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tonic_user')
    # ### end Alembic commands ###
