"""empty message

Revision ID: 0fbfc6641f53
Revises: 8cd5353fa358
Create Date: 2023-04-24 15:39:07.584097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fbfc6641f53'
down_revision = '8cd5353fa358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tonic_word_progress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tonic_word_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questions_answered', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tonic_user.id'], name='tonic_word_progress_user_id_fkey'),
    sa.ForeignKeyConstraint(['word_id'], ['tonic_question.id'], name='tonic_word_progress_word_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tonic_word_progress_pkey')
    )
    # ### end Alembic commands ###
