"""empty message

Revision ID: 13b48220f850
Revises: 0a02e4ad7bd2
Create Date: 2023-04-12 12:51:59.249148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b48220f850'
down_revision = '0a02e4ad7bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.drop_index('ix_datapoint_layer_id')
        batch_op.drop_index('ix_datapoint_query_id')
        batch_op.drop_constraint('data_point_query_id_fkey', type_='foreignkey')
        batch_op.drop_column('query_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('data_point_query_id_fkey', 'query', ['query_id'], ['id'])
        batch_op.create_index('ix_datapoint_query_id', ['query_id'], unique=False)
        batch_op.create_index('ix_datapoint_layer_id', ['layer_id'], unique=False)

    # ### end Alembic commands ###
