"""empty message

Revision ID: 1b1395cc8467
Revises: 0fbfc6641f53
Create Date: 2023-04-24 15:40:29.704105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1395cc8467'
down_revision = '0fbfc6641f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tonic_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tonic_score', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
