"""empty message

Revision ID: 45d6f99b65d1
Revises: 05af4b576e02
Create Date: 2023-04-12 16:26:37.310526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d6f99b65d1'
down_revision = '05af4b576e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
