"""empty message

Revision ID: 49372afba8d6
Revises: 87800a148071
Create Date: 2023-04-26 05:55:21.313901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49372afba8d6'
down_revision = '87800a148071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tonic_question', schema=None) as batch_op:
        batch_op.drop_index('ix_tonicquestion_word_id')

    with op.batch_alter_table('tonic_word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meaning', sa.Text(), nullable=True))
        batch_op.drop_index('ix_tonicword_lesson_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tonic_word', schema=None) as batch_op:
        batch_op.create_index('ix_tonicword_lesson_id', ['lesson_id'], unique=False)
        batch_op.drop_column('meaning')

    with op.batch_alter_table('tonic_question', schema=None) as batch_op:
        batch_op.create_index('ix_tonicquestion_word_id', ['word_id'], unique=False)

    # ### end Alembic commands ###
