"""empty message

Revision ID: 8cd5353fa358
Revises: 979c5b54e5f0
Create Date: 2023-04-24 15:07:53.366437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd5353fa358'
down_revision = '979c5b54e5f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tonic_word_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('questions_answered', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tonic_user.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['tonic_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tonic_word_progress')
    # ### end Alembic commands ###
