"""empty message

Revision ID: 94cd4f2853f2
Revises: 88ff8bfe9793
Create Date: 2023-04-19 15:38:40.808464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94cd4f2853f2'
down_revision = '88ff8bfe9793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tonic_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openai_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tonic_question', schema=None) as batch_op:
        batch_op.drop_column('openai_text')

    # ### end Alembic commands ###
