"""empty message

Revision ID: aa24d7b7795e
Revises: 83d2f759f016
Create Date: 2023-04-26 16:33:02.436192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa24d7b7795e'
down_revision = '83d2f759f016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tonic_lesson', schema=None) as batch_op:
        batch_op.drop_column('num_question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tonic_lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_question', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
