"""empty message

Revision ID: b499bd9608a5
Revises: a05596a7d8c4
Create Date: 2023-04-13 00:20:40.124020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b499bd9608a5'
down_revision = 'a05596a7d8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_field1_field2', ['address', 'email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.drop_constraint('uix_field1_field2', type_='unique')

    # ### end Alembic commands ###
